export const CHANGE_CURRENT_SONG = 'change-current-song'
export const CHANGE_PLAYLIST = 'change-playlist'
export const CHANGE_CURRENT_SONG_INDEX = 'change-current-song-index'
export const CHANGE_SEQUENCE = 'change-sequence'
export const CHANGE_LYRIC_LIST = 'change-lyric-list'
export const CHANGE_CURRENT_LYRIC_INDEX = 'change-current-lyric-index'
